In [ ]:

# Date : 20 feb 2025
# print () use
print ('can u give me the book')
print("Saraswati")
print('97799415')

ERROR: Error: object '.' not found

In [ ]:
# cat()
cat("had your dinner\n")
cat("yes")

In [ ]:
# variables
 name <- "ricky"
 age <- 22
 height <- 6.2
 address <- "konark"
 phn_no <- 65248515
 cat("my Name is : ",name)
 cat("\nMy Age Is : ",age)
 cat("\nMy height Is : ",height)
 cat("\nAddress Is : ", address)
 cat("\nphn no is : ", phn_no)

In [ ]:
# Calculation
 a <- 45
 b <-4
 c <- a+b
 cat("result is : ",c)

 a <- 654
 b <-74
 c <- a-b
 cat("\nresult is :",c)

 a <- 63
 b <- 23
 c <- a*b
 cat("\nresult is : ",c)

 a <- 2500
 b <- 50
 c <- a/b
 cat("\nresult is :",c)

In [ ]:
# task :
# input
# Enter your name : Nishant
# Enter your roll number : A234A

# Enter Java Marks out of 100 : 56
# Enter C++ Marks out of 100 : 50
# Enter go Marks out of 100 : 60
# Enter python Marks out of 100 : 75
# Enter R Marks out of 100 : 23

# Total = ?
# per% = ?


# Date : 25/feb/2004

Name <- "Nishant"
 Roll_number <- "A234A"
 paste()

Information <- paste("Detail : ", Name, Roll_number)

print(Information)

 Information <- paste0("Detail : ", Name, Roll_number)

 print(Information)

In [ ]:
# readline()

a <- as.integer(readline("Enter java marks out of 100 "))
b <- as.integer(readline("Enter c++ marks out of 100 "))
c <- as.integer(readline("Enter go marks out of 100 "))
d <- as.integer(readline("Enter python marks out of 100 "))
e <- as.integer(readline("Enter r marks out of 100 "))

 Result = a+b+c+d+e

  cat("\n  your result is : ",Result)

  #percentage
   Result3 = Result*100/500
   cat("\n  your result is : ",Result3,"%".)

In [ ]:
#OPERATOR
# if else statement

 x <- 250


 if (x %% 2==0){
  print("x is an even number")
  }else{
  print("x is an odd number")
}

In [ ]:
number1 = 521
number2 = 623
number3 = 21354
number4 = 410

if(number1 > number2 & number1 > number3 & number1 > number4){
  print("number1 is highest..")
} else if(number2 > number1 & number2 > number3 & number2 > number4){
  print("number2 is highest..")
}else if(number3 > number1 & number3 > number2 & number3 > number4){
print("number3 is highest..")
}else{
  print("number4 is highest..")
}

In [ ]:
# ifelse(test_expression, yes_expression, no_expression)
x = 52
y = 65
ifelse(x > y,"x is smallest","x is not smallest")

In [ ]:
# loop
 for(i in 3:20){
  print(i)
 }

In [ ]:
for(i in 4:12){
  cat(i*4,'\n')
}

In [ ]:
#find the odd number between 1 to 30
 for(i in 1:30){
  if(i %% 2 != 0){
    cat( i ,"even" , '\n')
  }else{
    cat(i ,"odd" , '\n')
  }
 }

In [ ]:
# while loop
x = 5
while (x <= 25){
  print(x)
  x = x + 1
}

[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 25

In [ ]:
#repeat loop
add <- 2
repeat {
cat ("addition :", add, "\n")
add <- add + 1
if (add > 25){
    break
}
}

addition : 2
addition : 3
addition : 4
addition : 5
addition : 6
addition : 7
addition : 8
addition : 9
addition : 10
addition : 11
addition : 12
addition : 13
addition : 14
addition : 15
addition : 16
addition : 17
addition : 18
addition : 19
addition : 20
addition : 21
addition : 22
addition : 23
addition : 24
addition : 25

In [ ]:
for ( i in 1:20){
  if(i>9){
    next
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9

In [ ]:
# function
data <- function(){
  cat("had your dinner")
  cat("\ncan u  give the book")

}
data()

had your dinner
can u  give the book

In [ ]:
# function with argument.......
 data <- function(x,y,z){
  result <- x*y*z
  cat("\n result :",result)
 }

In [ ]:
data(57,756,87)
data(12,23,554)

 result : 3749004
 result : 152904

In [ ]:
# BILL
bill <- function(quantity,price,gst){
   total_amount <-price*quantity
 gst_amount <- total_amount*gst/100
 total_price <- total_amount + gst_amount
 cat("\n................bill...........\n")
 cat("\nprice :",price,"/-")
 cat("\nquantity :",quantity, "/-")
 cat("\nGST :",gst,"%")
 cat("\nGST_amount =",gst_amount,"/-")
 cat("\ntotal_amount =",total_amount,"/-")
 cat("\ntotal_price(with GST) =",total_price,"/-")
}

In [ ]:
bill(4,450,12)
bill(12,8757,6)
bill(67,67576,8)

................bill...........

price : 450 /-
quantity : 4 /-
GST : 12 %
GST_amount = 216 /-
total_amount = 1800 /-
total_price(with GST) = 2016 /-
................bill...........

price : 8757 /-
quantity : 12 /-
GST : 6 %
GST_amount = 6305.04 /-
total_amount = 105084 /-
total_price(with GST) = 111389 /-
................bill...........

price : 67576 /-
quantity : 67 /-
GST : 8 %
GST_amount = 362207.4 /-
total_amount = 4527592 /-
total_price(with GST) = 4889799 /-

In [ ]:
# FUNCTION WITH RETURN

 numbers <- function(){
  return(44754)
 }



 data <- function(){
  return("suprava")
 }

In [ ]:
x <- numbers()
print(x)

[1] 44754

In [ ]:
y <- data()
print(y)

[1] "suprava"

In [ ]:
#FUNCTION WITH RETURN TYPE ARG
multi <- function(number1,number2){
  result <- number1 * number2
  return(result)
}

In [ ]:
print(multi(4562,544))

[1] 2481728

In [ ]:
# string function
 data = ("finish your food")
 print(nchar(data))

 #substring extraction
 substr(data,7,14)

 #string manipulation
 toupper(data)

[1] 16

[1] " your fo"

[1] "FINISH YOUR FOOD"

In [ ]:
# string comparision
 x <- "rickyy"
 y <- "suprava"
  result <- x > y
  print(result)

[1] FALSE

In [ ]:
# STRING INTERPOLATION
 name <- "ricky"
 age <- 22
 weight <- 62

 information <- sprintf("Hallo, my name is %s and i am %d years old and weight %g",name, age, weight)
 cat("information:",information,"\n")

In [ ]:
# spliting and joining  strings
 data <- "ricky,suprava,vicky"
 split_data <- strsplit(data,",")[[1]]
 joined_data <- paste(split_data,collapse = ". ")
 cat("joined_data:", joined_data,"\n")

joined_data: ricky. suprava. vicky

In [ ]:
# R VECTORS
 detail <- c('su','liza','ricky','vicky','roja')
 detail
 print(detail)
 cat(detail)

In [ ]:

# vector function

 data = c(45,657,75.754,543)

  sum(data)
  length(data)
  mean(data)
  data^3

[1] 1320.754

[1] 4

[1] 330.1885

[1]     91125.0 283593393.0    434727.1 160103007.0

In [ ]:
# matrix


numeric_matrix <-  matrix(data = 34.87,nrow = 3,ncol = 3)
numeric_matrix

     [,1]  [,2]  [,3]
[1,] 34.87 34.87 34.87
[2,] 34.87 34.87 34.87
[3,] 34.87 34.87 34.87

In [ ]:
# create a matrix on R

data = c(43,76,83,34,12,65,39,83,96)
 numeric_matrix <- matrix(data = data,nrow = 3,ncol = 3)
 numeric_matrix
  print(numeric_matrix[3,2])

     [,1] [,2] [,3]
[1,] 43   34   39
[2,] 76   12   83
[3,] 83   65   96

[1] 65

In [ ]:
# vector operation
vector1 <- c(3,8,9)
vector2 <- c(8,5,1)
cat(vector1+vector2)
cat("\n",vector1*vector2)

# comparision on numeric value
cat("\n",vector1 > vector2)

#logical operation on logical variables
cat("\n",vector1 < 4 & vector2 >=3)

# accessing element
 data <- c(34,77,22,54,97,28,32)
data[4]

vector <- c(a = 10,b = 45,c = 33)
cat(vector)

11 13 10
 24 40 9
 FALSE TRUE TRUE
 TRUE FALSE FALSE

[1] 54

10 45 33

#
data = list(

In [1]:
# list

 data = list(name="ricky",age= "22",salary = "4521000",subject= c("c","python","java","sql"))
  data

  # acess data
  data$name
  data$subject
  data$subject[3]
  data[2]
  data[[3]]

 # update data
  data$age = 25
  data
  # delete data
  data$salary = NULL
  data

  length(data)
  names(data)
  str(data)

$name
[1] "ricky"

$age
[1] "22"

$salary
[1] "4521000"

$subject
[1] "c"      "python" "java"   "sql"

[1] "ricky"

[1] "c"      "python" "java"   "sql"

[1] "java"

$age
[1] "22"

[1] "4521000"

$name
[1] "ricky"

$age
[1] 25

$salary
[1] "4521000"

$subject
[1] "c"      "python" "java"   "sql"

$name
[1] "ricky"

$age
[1] 25

$subject
[1] "c"      "python" "java"   "sql"

[1] 3

[1] "name"    "age"     "subject"

List of 3
 $ name   : chr "ricky"
 $ age    : num 25
 $ subject: chr [1:4] "c" "python" "java" "sql"

In [ ]:
# ARRAY
 data_matrix = matrix(3:30, nrow=4,ncol = 7)
 data_matrix
   my_array = array(data_matrix,dim = c(4,7,2))
   my_array

   my_array[23]
   my_array[40]

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 3     7   11   15   19   23   27
[2,] 4     8   12   16   20   24   28
[3,] 5     9   13   17   21   25   29
[4,] 6    10   14   18   22   26   30

, , 1

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    3    7   11   15   19   23   27
[2,]    4    8   12   16   20   24   28
[3,]    5    9   13   17   21   25   29
[4,]    6   10   14   18   22   26   30

, , 2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    3    7   11   15   19   23   27
[2,]    4    8   12   16   20   24   28
[3,]    5    9   13   17   21   25   29
[4,]    6   10   14   18   22   26   30

[1] 25

[1] 14

In [ ]:
# creating a 3 dimensional aaray with dimension names

data_array = array(1:30, dim = c(5,6,2),
dimnames = list(c("l","b","y","C","s"),c("h","t","s","e","x","w"),c("m","n")))
data_array

dim(data_array)
dimnames(data_array)

, , m

  h  t  s  e  x  w
l 1  6 11 16 21 26
b 2  7 12 17 22 27
y 3  8 13 18 23 28
C 4  9 14 19 24 29
s 5 10 15 20 25 30

, , n

  h  t  s  e  x  w
l 1  6 11 16 21 26
b 2  7 12 17 22 27
y 3  8 13 18 23 28
C 4  9 14 19 24 29
s 5 10 15 20 25 30

[1] 5 6 2

[[1]]
[1] "l" "b" "y" "C" "s"

[[2]]
[1] "h" "t" "s" "e" "x" "w"

[[3]]
[1] "m" "n"

In [ ]:
# data frame
# creating a data frame
information = data.frame(
  name = c("ricky","mili","puja","nitin","liza"),
  age = c(34,22,12,41,20),
  sub = c("phy","chem","math","it","os"),
  grade = c("A","G","R","D","c")
)

print(information)

information$name[5]

# adding a new coloum
information$result = c("pass","fail","pass","fail","pass")
print(information)


names(information)

nchar(information)

nrow(information)

summary(information)

   name age  sub grade
1 ricky  34  phy     A
2  mili  22 chem     G
3  puja  12 math     R
4 nitin  41   it     D
5  liza  20   os     c

[1] "liza"

   name age  sub grade result
1 ricky  34  phy     A   pass
2  mili  22 chem     G   fail
3  puja  12 math     R   pass
4 nitin  41   it     D   fail
5  liza  20   os     c   pass

[1] "name"   "age"    "sub"    "grade"  "result"

  name    age    sub  grade result
    43     21     36     26     41

[1] 5

     name                age           sub               grade
 Length:5           Min.   :12.0   Length:5           Length:5
 Class :character   1st Qu.:20.0   Class :character   Class :character
 Mode  :character   Median :22.0   Mode  :character   Mode  :character
                    Mean   :25.8
                    3rd Qu.:34.0
                    Max.   :41.0
    result
 Length:5
 Class :character
 Mode  :character

In [ ]:
# Exporting the data frame to a CSV file
write.csv(information, "data_frame.csv", row.names = FALSE)

In [ ]:
# Importing data from a CSV file
df_imported <- read.csv("all_t20_world_cup_matches_results.csv")
# print(df_imported)

df = data.frame(df_imported)

names(df)
ncol(df)
nrow(df)
summary(df)

[1] "Team1"          "Team2"          "Winner"         "Margin"
[5] "Ground"         "Match.Date"     "T.20.Int.Match"

[1] 7

[1] 317

    Team1              Team2              Winner             Margin
 Length:317         Length:317         Length:317         Length:317
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
    Ground           Match.Date        T.20.Int.Match
 Length:317         Length:317         Length:317
 Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character